#!/bin/bash

cd ~/workspace/cppStudy

rm -rf build
mkdir build
cd build
cmake ..
cmake --build .

exit

chmod 775 CM
lscpu
rm -rf build && mkdir build && cd build && cmake .. && make -j$(nproc) && cd ..

printenv | grep LD_LIBRARY_PATH
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/workspace/lib

export LD_LIBRARY_PATH=.
