"
" :sp
" :vs
" :close :only
"
" :set list and :set nolist
"
" :set noexpandtab for Makefile
"
" vim -b binary.bin
" :autocmd! BinaryXXD
" :set nobin
"

set number

set tabstop=4
set shiftwidth=4
" set softtabstop=4
" set expandtab

" set list listchars=tab:▸\ ,eol:↲

" nnoremap <space>. :<c-u>tabedit $MYVIMRC<CR>
" nnoremap <space>. :<c-u>tabedit ~/.vimrc<CR>

" inoremap jj <Esc>


augroup BinaryXXD
  autocmd!
  autocmd BufReadPost * if &binary | silent %!xxd -g 1
  autocmd BufReadPost * set ft=xxd | endif
  autocmd BufWritePre * if &binary | %!xxd -r | endif
  autocmd BufWritePost * if &binary | silent %!xxd -g 1
  autocmd BufWritePost * set nomod | endif
augroup END